// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "arrow":return img`
. . 8 . . 
. . 8 . . 
. . 8 . . 
. . 8 . . 
8 8 8 8 8 
. 8 8 8 . 
. . 8 . . 
`;
            case "image3":
            case "mySpriteHeart":return img`
....................
....................
....................
....................
....................
......bbb...bbb.....
.....bdddb.bddcb....
....bdddddbddbccb...
....bdddddddbbccb...
....bddddddbbcccb...
.....bddddbbcccb....
......bbdbbcccb.....
.......bcccccb......
........bcccb.......
.........bcb........
..........b.........
....................
....................
....................
....................
`;
            case "image1":
            case "cupid hearts":return img`
....................
....................
....................
....33.3....33......
...3..3.3..3..33....
...3.222.33.222.3...
..3.21122..22222.3..
...32122222222223...
..3.222222222222.3..
..3..22222222b2..3..
...332222222bb233...
...3.2222222222.3...
....33..2222..33....
......33222233......
.......3.22.3.......
.......33..3........
.........33.........
....................
....................
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
